version: '3.8'

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    restart: 'always'
    expose:
      - "3306"
    environment:
      # Password User ROOT in Container
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # Database name in Container
     MYSQL_DATABASE: ${MYSQL_DATABASE}
      # User name in Container
     MYSQL_USER: ${MYSQL_USER}
      # Password User in Container
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
  project:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ENV=production
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql_data: